services:
  make-dummy:
    image: alpine:latest
    volumes:
      - .:/dummy
    command: sh -c "[ -f /dummy/mlruns.db ] || touch /dummy/mlruns.db"
  ml-pipeline:
    build: .
    command: sh -c "uv run main.py && uv run mlflow server --host 0.0.0.0 --port 50 --backend-store-uri ${MLFLOW_TRACKING_URI}"
    ports:
      - "5050:50"
    volumes:
      - ./mlruns.db:/app/mlruns.db
      - ./mlruns:/app/mlruns
    environment:
      - MODE=test
      - MLFLOW_TRACKING_URI=sqlite:///mlruns.db